/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package My_Forms;

import My_Classes.Func_Class;
import My_Classes.Member;
import My_Classes.Movies;
import My_Classes.Users;
import java.awt.Color;
import java.awt.Container;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Administrator
 */
public class MoviesForm extends javax.swing.JFrame {

    Border buttonBorder1 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
    Border buttonBorder0 = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(44, 133, 142));

    My_Classes.Func_Class func = new Func_Class();
    My_Classes.Movies movies = new Movies();

    JLabel[] labels_tab = new JLabel[6];
    JLabel[] labels_tab1 = new JLabel[6];

    MoviesListForm move = new MoviesListForm();
    MyTicketForm ticket = new MyTicketForm();
    TimeForm time = new TimeForm();
    MemberListForm membersListF = new MemberListForm();
    Review review = new Review();

    public MoviesForm() throws SQLException {
        initComponents();
        func.displayImage(jLabel3.getWidth(), jLabel3.getHeight(), null, "/My_Images/cine3.png", jLabel3);
        func.displayImage(jLabel_Dashboard_user.getWidth(), jLabel_Dashboard_user.getHeight(), null, "/My_Images/kon.png", jLabel_Dashboard_user);
        /*func.displayImage(jLabel_Image_1.getWidth(), jLabel_Image_1.getHeight(),null, "/My_Images/c1.jpg", jLabel_Image_1);
       func.displayImage(jLabel_Image_2.getWidth(), jLabel_Image_2.getHeight(),null, "/My_Images/c2.jpg", jLabel_Image_2);
       func.displayImage(jLabel_Image_3.getWidth(), jLabel_Image_3.getHeight(),null, "/My_Images/c3.jpg", jLabel_Image_3);
       func.displayImage(jLabel_Image_4.getWidth(), jLabel_Image_4.getHeight(),null, "/My_Images/c4.jpg", jLabel_Image_4);
       func.displayImage(jLabel_Image_5.getWidth(), jLabel_Image_5.getHeight(),null, "/My_Images/c5.jpg", jLabel_Image_5);
       func.displayImage(jLabel_Image_6.getWidth(), jLabel_Image_6.getHeight(),null, "/My_Images/c6.jpg", jLabel_Image_6);*/

        //addBorders();
        //buttonsHoverEffect();
        //displayCount();
        labels_tab[0] = jLabel_Image_1;
        labels_tab[1] = jLabel_Image_3;
        labels_tab[2] = jLabel_Image_8;
        labels_tab[3] = jLabel_Image_4;
        labels_tab[4] = jLabel_Image_5;
        labels_tab[5] = jLabel_Image_6;

        movies.displayBooksCover(labels_tab);

        My_Classes.Movies SelectedMovies;

        SelectedMovies = movies.getBookById(6);
        jLabel1.setText(SelectedMovies.getName());
        jLabel2.setText(movies.getBookById(5).getName());
        jLabel5.setText(movies.getBookById(4).getName());
        jLabel6.setText(movies.getBookById(1).getName());
        jLabel7.setText(movies.getBookById(2).getName());
        jLabel8.setText(movies.getBookById(3).getName());

        genre1.setText(movies.getBookById(6).getGenre());
        genre2.setText(movies.getBookById(5).getGenre());
        genre3.setText(movies.getBookById(4).getGenre());
        genre4.setText(movies.getBookById(1).getGenre());
        genre5.setText(movies.getBookById(2).getGenre());
        genre6.setText(movies.getBookById(3).getGenre());

        time1.setText(movies.getBookById(6).getTimes());
        time2.setText(movies.getBookById(5).getTimes());
        time3.setText(movies.getBookById(4).getTimes());
        time4.setText(movies.getBookById(1).getTimes());
        time5.setText(movies.getBookById(2).getTimes());
        time6.setText(movies.getBookById(3).getTimes());

        setResizable(false);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Image_7 = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jButton_Members_List_ = new javax.swing.JButton();
        jButton_Books_List_ = new javax.swing.JButton();
        jButton_Books_List_1 = new javax.swing.JButton();
        jLabel_Dashboard_user = new javax.swing.JLabel();
        jButton_Books_List_4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel_WelcomeUsername = new javax.swing.JTextField();
        jLabel_WelcomeUsername1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Review = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Image_1 = new javax.swing.JLabel();
        jButton_Books_List_5 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JButton();
        jButton7 = new rojerusan.RSMaterialButtonRectangle();
        genre1 = new rojerusan.RSMaterialButtonRectangle();
        time1 = new rojerusan.RSMaterialButtonRectangle();
        jPanel10 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_Image_3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JButton();
        jButton8 = new rojerusan.RSMaterialButtonRectangle();
        genre2 = new rojerusan.RSMaterialButtonRectangle();
        time2 = new rojerusan.RSMaterialButtonRectangle();
        jPanel11 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_Image_8 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JButton();
        jButton9 = new rojerusan.RSMaterialButtonRectangle();
        genre3 = new rojerusan.RSMaterialButtonRectangle();
        time3 = new rojerusan.RSMaterialButtonRectangle();
        jPanel15 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_Image_6 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JButton();
        jButton10 = new rojerusan.RSMaterialButtonRectangle();
        genre4 = new rojerusan.RSMaterialButtonRectangle();
        time4 = new rojerusan.RSMaterialButtonRectangle();
        jPanel17 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel_Image_5 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JButton();
        jButton11 = new rojerusan.RSMaterialButtonRectangle();
        genre5 = new rojerusan.RSMaterialButtonRectangle();
        time5 = new rojerusan.RSMaterialButtonRectangle();
        jPanel21 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel_Image_4 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JButton();
        jButton12 = new rojerusan.RSMaterialButtonRectangle();
        genre6 = new rojerusan.RSMaterialButtonRectangle();
        time6 = new rojerusan.RSMaterialButtonRectangle();
        menuBar = new javax.swing.JMenuBar();

        jLabel_Image_7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Image_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Image_7MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        desktopPane.setBackground(new java.awt.Color(211, 210, 221));
        desktopPane.setMaximumSize(new java.awt.Dimension(1497, 718));
        desktopPane.setPreferredSize(new java.awt.Dimension(1497, 718));

        jPanel18.setBackground(new java.awt.Color(31, 29, 54));

        jPanel19.setBackground(new java.awt.Color(108, 171, 188));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton_Members_List_.setFont(new java.awt.Font("Pridi SemiBold", 1, 14)); // NOI18N
        jButton_Members_List_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Members_List_.setText("Members");
        jButton_Members_List_.setContentAreaFilled(false);
        jButton_Members_List_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Members_List_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Members_List_ActionPerformed(evt);
            }
        });

        jButton_Books_List_.setFont(new java.awt.Font("Pridi SemiBold", 1, 14)); // NOI18N
        jButton_Books_List_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Books_List_.setText("Movies");
        jButton_Books_List_.setContentAreaFilled(false);
        jButton_Books_List_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Books_List_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Books_List_ActionPerformed(evt);
            }
        });

        jButton_Books_List_1.setFont(new java.awt.Font("Pridi SemiBold", 1, 14)); // NOI18N
        jButton_Books_List_1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Books_List_1.setText("My Ticket");
        jButton_Books_List_1.setContentAreaFilled(false);
        jButton_Books_List_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Books_List_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Books_List_1ActionPerformed(evt);
            }
        });

        jLabel_Dashboard_user.setBackground(new java.awt.Color(31, 29, 54));
        jLabel_Dashboard_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Dashboard_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Dashboard_userMouseClicked(evt);
            }
        });

        jButton_Books_List_4.setFont(new java.awt.Font("Pridi SemiBold", 1, 24)); // NOI18N
        jButton_Books_List_4.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Books_List_4.setContentAreaFilled(false);
        jButton_Books_List_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Books_List_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Books_List_4ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jLabel_WelcomeUsername.setEditable(false);
        jLabel_WelcomeUsername.setBackground(new java.awt.Color(31, 29, 54));
        jLabel_WelcomeUsername.setFont(new java.awt.Font("Pridi SemiBold", 1, 18)); // NOI18N
        jLabel_WelcomeUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_WelcomeUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabel_WelcomeUsername.setText("Hi !");
        jLabel_WelcomeUsername.setBorder(null);
        jLabel_WelcomeUsername.setCaretColor(new java.awt.Color(108, 171, 188));
        jLabel_WelcomeUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabel_WelcomeUsernameActionPerformed(evt);
            }
        });

        jLabel_WelcomeUsername1.setEditable(false);
        jLabel_WelcomeUsername1.setBackground(new java.awt.Color(31, 29, 54));
        jLabel_WelcomeUsername1.setFont(new java.awt.Font("Pridi SemiBold", 1, 18)); // NOI18N
        jLabel_WelcomeUsername1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_WelcomeUsername1.setBorder(null);
        jLabel_WelcomeUsername1.setCaretColor(new java.awt.Color(108, 171, 188));
        jLabel_WelcomeUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabel_WelcomeUsername1ActionPerformed(evt);
            }
        });

        jLabel4.setText("jLabel4");

        Review.setFont(new java.awt.Font("Pridi SemiBold", 1, 14)); // NOI18N
        Review.setForeground(new java.awt.Color(255, 255, 255));
        Review.setText("Review");
        Review.setContentAreaFilled(false);
        Review.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Review.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Books_List_4)
                .addGap(149, 149, 149)
                .addComponent(jLabel_WelcomeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_WelcomeUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton_Books_List_)
                .addGap(18, 18, 18)
                .addComponent(jButton_Members_List_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Books_List_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Review)
                .addGap(31, 31, 31)
                .addComponent(jLabel_Dashboard_user, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Books_List_4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel_Dashboard_user, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Members_List_)
                            .addComponent(jButton_Books_List_)
                            .addComponent(jButton_Books_List_1)
                            .addComponent(Review)))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_WelcomeUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_WelcomeUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1204, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 1191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        desktopPane.add(jPanel1);
        jPanel1.setBounds(0, 0, 1190, 60);

        jPanel8.setBackground(new java.awt.Color(211, 210, 221));

        jPanel2.setBackground(new java.awt.Color(31, 29, 54));

        jLabel_Image_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Image_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Image_1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_Books_List_5.setFont(new java.awt.Font("Pridi SemiBold", 1, 24)); // NOI18N
        jButton_Books_List_5.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Books_List_5.setText("Now Showing");
        jButton_Books_List_5.setContentAreaFilled(false);
        jButton_Books_List_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Books_List_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Books_List_5ActionPerformed(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(211, 210, 221));

        jLabel1.setBackground(new java.awt.Color(163, 189, 196));
        jLabel1.setFont(new java.awt.Font("Pridi SemiBold", 1, 16)); // NOI18N
        jLabel1.setText("My Ticket");
        jLabel1.setContentAreaFilled(false);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton7.setBackground(new java.awt.Color(254, 194, 96));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Buy Now");
        jButton7.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        genre1.setBackground(new java.awt.Color(255, 255, 255));
        genre1.setForeground(new java.awt.Color(0, 0, 0));
        genre1.setText("Genre");
        genre1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N

        time1.setBackground(new java.awt.Color(255, 255, 255));
        time1.setForeground(new java.awt.Color(0, 0, 0));
        time1.setText("time");
        time1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genre1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genre1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(31, 29, 54));

        jLabel_Image_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Image_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Image_3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(211, 210, 221));

        jLabel2.setBackground(new java.awt.Color(163, 189, 196));
        jLabel2.setFont(new java.awt.Font("Pridi SemiBold", 1, 16)); // NOI18N
        jLabel2.setText("My Ticket");
        jLabel2.setContentAreaFilled(false);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton8.setBackground(new java.awt.Color(254, 194, 96));
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Buy Now");
        jButton8.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        genre2.setBackground(new java.awt.Color(255, 255, 255));
        genre2.setForeground(new java.awt.Color(0, 0, 0));
        genre2.setText("Genre");
        genre2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N

        time2.setBackground(new java.awt.Color(255, 255, 255));
        time2.setForeground(new java.awt.Color(0, 0, 0));
        time2.setText("time");
        time2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genre2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genre2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(31, 29, 54));

        jLabel_Image_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Image_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Image_8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_8, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_8, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(211, 210, 221));

        jLabel5.setBackground(new java.awt.Color(163, 189, 196));
        jLabel5.setFont(new java.awt.Font("Pridi SemiBold", 1, 16)); // NOI18N
        jLabel5.setText("My Ticket");
        jLabel5.setContentAreaFilled(false);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton9.setBackground(new java.awt.Color(254, 194, 96));
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("Buy Now");
        jButton9.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        genre3.setBackground(new java.awt.Color(255, 255, 255));
        genre3.setForeground(new java.awt.Color(0, 0, 0));
        genre3.setText("Genre");
        genre3.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N

        time3.setBackground(new java.awt.Color(255, 255, 255));
        time3.setForeground(new java.awt.Color(0, 0, 0));
        time3.setText("time");
        time3.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genre3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genre3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(31, 29, 54));

        jLabel_Image_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Image_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Image_6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_6, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_6, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(211, 210, 221));

        jLabel6.setBackground(new java.awt.Color(163, 189, 196));
        jLabel6.setFont(new java.awt.Font("Pridi SemiBold", 1, 16)); // NOI18N
        jLabel6.setText("My Ticket");
        jLabel6.setContentAreaFilled(false);
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton10.setBackground(new java.awt.Color(254, 194, 96));
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("Buy Now");
        jButton10.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        genre4.setBackground(new java.awt.Color(255, 255, 255));
        genre4.setForeground(new java.awt.Color(0, 0, 0));
        genre4.setText("Genre");
        genre4.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N

        time4.setBackground(new java.awt.Color(255, 255, 255));
        time4.setForeground(new java.awt.Color(0, 0, 0));
        time4.setText("time");
        time4.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genre4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genre4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(31, 29, 54));

        jLabel_Image_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Image_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Image_5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_5, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_5, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel20.setBackground(new java.awt.Color(211, 210, 221));

        jLabel7.setBackground(new java.awt.Color(163, 189, 196));
        jLabel7.setFont(new java.awt.Font("Pridi SemiBold", 1, 16)); // NOI18N
        jLabel7.setText("My Ticket");
        jLabel7.setContentAreaFilled(false);
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton11.setBackground(new java.awt.Color(254, 194, 96));
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("Buy Now");
        jButton11.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        genre5.setBackground(new java.awt.Color(255, 255, 255));
        genre5.setForeground(new java.awt.Color(0, 0, 0));
        genre5.setText("Genre");
        genre5.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N

        time5.setBackground(new java.awt.Color(255, 255, 255));
        time5.setForeground(new java.awt.Color(0, 0, 0));
        time5.setText("time");
        time5.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genre5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genre5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(new java.awt.Color(31, 29, 54));

        jLabel_Image_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Image_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Image_4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_4, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_4, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel22.setBackground(new java.awt.Color(211, 210, 221));

        jLabel8.setBackground(new java.awt.Color(163, 189, 196));
        jLabel8.setFont(new java.awt.Font("Pridi SemiBold", 1, 16)); // NOI18N
        jLabel8.setText("My Ticket");
        jLabel8.setContentAreaFilled(false);
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton12.setBackground(new java.awt.Color(254, 194, 96));
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("Buy Now");
        jButton12.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        genre6.setBackground(new java.awt.Color(255, 255, 255));
        genre6.setForeground(new java.awt.Color(0, 0, 0));
        genre6.setText("Genre");
        genre6.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N

        time6.setBackground(new java.awt.Color(255, 255, 255));
        time6.setForeground(new java.awt.Color(0, 0, 0));
        time6.setText("time");
        time6.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genre6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genre6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Books_List_5))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(88, 88, 88)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(88, 88, 88)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jButton_Books_List_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        desktopPane.add(jPanel8);
        jPanel8.setBounds(0, 60, 1190, 820);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Members_List_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Members_List_ActionPerformed
        // show the Members List form
        
        if (membersListF == null || membersListF.isClosed()) {

            membersListF.setTitle("Majar Cineplex");
            membersListF.setFrameIcon(null);
            BasicInternalFrameUI ui = (BasicInternalFrameUI) membersListF.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(membersListF);

            membersListF.setVisible(true);
        } else {
            membersListF.setTitle("Majar Cineplex");
            membersListF.setFrameIcon(null);
            BasicInternalFrameUI ui = (BasicInternalFrameUI) membersListF.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(membersListF);
            membersListF.setLocation(this.getWidth()/2 - membersListF.getWidth()/2, this.getHeight()/2 - membersListF.getHeight()/2);
            
            membersListF.setVisible(true);
        }
    }//GEN-LAST:event_jButton_Members_List_ActionPerformed

    private void jButton_Books_List_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Books_List_ActionPerformed
        // show the books list form
        if (move == null || move.isClosed()) {

            move.setTitle("Majar Cineplex");
            move.setFrameIcon(null);
            BasicInternalFrameUI ui = (BasicInternalFrameUI) move.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(move);

            move.setVisible(true);
        } else {
            move.setTitle("Majar Cineplex");
            move.setFrameIcon(null);
            BasicInternalFrameUI ui = (BasicInternalFrameUI) move.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(move);
            move.setLocation(this.getWidth()/2 - move.getWidth()/2, this.getHeight()/2 - move.getHeight()/2);
            
            move.setVisible(true);
        }
    }//GEN-LAST:event_jButton_Books_List_ActionPerformed

    private void jButton_Books_List_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Books_List_1ActionPerformed
        // TODO add your handling code here:
                
        if (ticket == null || ticket.isClosed()) {

            ticket.setTitle("Majar Cineplex");
            ticket.setFrameIcon(null);
            BasicInternalFrameUI ui = (BasicInternalFrameUI) ticket.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(ticket);

            ticket.setVisible(true);
        } else {
           ticket.setTitle("Majar Cineplex");
            ticket.setFrameIcon(null);
            BasicInternalFrameUI ui = (BasicInternalFrameUI) ticket.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(ticket);
            ticket.setLocation(this.getWidth()/2 - ticket.getWidth()/2, this.getHeight()/2 - ticket.getHeight()/2);
            
            ticket.setVisible(true);
        }
    }//GEN-LAST:event_jButton_Books_List_1ActionPerformed

    private void jLabel_Dashboard_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Dashboard_userMouseClicked
        // TODO add your handling code here:
        My_Classes.Users user = new Users();
        Member member = new Member();
        EditMemberForm membersListF = new EditMemberForm();
        membersListF.jTextField1.setText(jLabel_WelcomeUsername1.getText());
        try {
            member.getMemberByFirstname(jLabel_WelcomeUsername1.getText());
            membersListF.jLabel2.setText(jLabel4.getText());
            membersListF.jTextField6.setText(member.getMemberByFirstname(jLabel_WelcomeUsername1.getText()).getLastName());
            membersListF.jTextField6.setText(member.getMemberByFirstname(jLabel_WelcomeUsername1.getText()).getLastName());
            membersListF.jTextField2.setText(member.getMemberByFirstname(jLabel_WelcomeUsername1.getText()).getEmail());
            membersListF.jTextField4.setText(member.getMemberByFirstname(jLabel_WelcomeUsername1.getText()).getPhone());

            membersListF.jComboBox1.setSelectedItem(member.getMemberByFirstname(jLabel_WelcomeUsername1.getText()).getGender());
            byte[] image = member.getMemberByFirstname(jLabel_WelcomeUsername1.getText()).getPicture();

            func.displayImage(125, 80, image, "", membersListF.jLabel21);
        } catch (SQLException ex) {
            //Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        membersListF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_Dashboard_userMouseClicked

    private void jButton_Books_List_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Books_List_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Books_List_4ActionPerformed

    private void jLabel_WelcomeUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabel_WelcomeUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_WelcomeUsernameActionPerformed

    private void jLabel_WelcomeUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabel_WelcomeUsername1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel_WelcomeUsername1ActionPerformed

    private void jLabel_Image_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Image_1MouseClicked
        // TODO add your handling code here:
        EditMemberForm editMbrF = new EditMemberForm();
        editMbrF.setVisible(true);
    }//GEN-LAST:event_jLabel_Image_1MouseClicked

    private void jButton_Books_List_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Books_List_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Books_List_5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       // time.setVisible(true);
        if (time == null || time.isClosed()) {

            time.setTitle("Majar Cineplex");
            time.setFrameIcon(null);
            try {
                time.name_cinima.setText(movies.getBookById(6).getName());
            } catch (SQLException ex) {
                Logger.getLogger(MoviesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            BasicInternalFrameUI ui = (BasicInternalFrameUI) time.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(time);

            time.setVisible(true);
        } else {
           time.setTitle("Majar Cineplex");
            time.setFrameIcon(null);
            try {
                time.name_cinima.setText(movies.getBookById(6).getName());
            } catch (SQLException ex) {
                Logger.getLogger(MoviesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            BasicInternalFrameUI ui = (BasicInternalFrameUI) time.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(time);
            time.setLocation(this.getWidth()/2 - time.getWidth()/2, this.getHeight()/2 - time.getHeight()/2);
            
            time.setVisible(true);
        }
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel_Image_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Image_3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Image_3MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        //time.setVisible(true);
        if (time == null || time.isClosed()) {

            time.setTitle("Majar Cineplex");
            time.setFrameIcon(null);
            try {
                time.name_cinima.setText(movies.getBookById(5).getName());
            } catch (SQLException ex) {
                Logger.getLogger(MoviesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            BasicInternalFrameUI ui = (BasicInternalFrameUI) time.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(time);

            time.setVisible(true);
        } else {
           time.setTitle("Majar Cineplex");
            time.setFrameIcon(null);
            try {
                time.name_cinima.setText(movies.getBookById(5).getName());
            } catch (SQLException ex) {
                Logger.getLogger(MoviesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            BasicInternalFrameUI ui = (BasicInternalFrameUI) time.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(time);
            time.setLocation(this.getWidth()/2 - time.getWidth()/2, this.getHeight()/2 - time.getHeight()/2);
            
            time.setVisible(true);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jLabel_Image_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Image_7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Image_7MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        //time.setVisible(true);
        if (time == null || time.isClosed()) {

            time.setTitle("Majar Cineplex");
            time.setFrameIcon(null);
            try {
                time.name_cinima.setText(movies.getBookById(4).getName());
            } catch (SQLException ex) {
                Logger.getLogger(MoviesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            BasicInternalFrameUI ui = (BasicInternalFrameUI) time.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(time);

            time.setVisible(true);
        } else {
           time.setTitle("Majar Cineplex");
            time.setFrameIcon(null);
            try {
                time.name_cinima.setText(movies.getBookById(4).getName());
            } catch (SQLException ex) {
                Logger.getLogger(MoviesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            BasicInternalFrameUI ui = (BasicInternalFrameUI) time.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(time);
            time.setLocation(this.getWidth()/2 - time.getWidth()/2, this.getHeight()/2 - time.getHeight()/2);
            
            time.setVisible(true);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jLabel_Image_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Image_6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Image_6MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        time.setVisible(true);
        if (time == null || time.isClosed()) {

            time.setTitle("Majar Cineplex");
            time.setFrameIcon(null);
            try {
                time.name_cinima.setText(movies.getBookById(1).getName());
            } catch (SQLException ex) {
                Logger.getLogger(MoviesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            BasicInternalFrameUI ui = (BasicInternalFrameUI) time.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(time);

            time.setVisible(true);
        } else {
           time.setTitle("Majar Cineplex");
            time.setFrameIcon(null);
            try {
                time.name_cinima.setText(movies.getBookById(1).getName());
            } catch (SQLException ex) {
                Logger.getLogger(MoviesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            BasicInternalFrameUI ui = (BasicInternalFrameUI) time.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(time);
            time.setLocation(this.getWidth()/2 - time.getWidth()/2, this.getHeight()/2 - time.getHeight()/2);
            
            time.setVisible(true);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jLabel_Image_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Image_5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Image_5MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        //time.setVisible(true);
        if (time == null || time.isClosed()) {

            time.setTitle("Majar Cineplex");
            time.setFrameIcon(null);
            try {
                time.name_cinima.setText(movies.getBookById(2).getName());
            } catch (SQLException ex) {
                Logger.getLogger(MoviesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            BasicInternalFrameUI ui = (BasicInternalFrameUI) time.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(time);

            time.setVisible(true);
        } else {
           time.setTitle("Majar Cineplex");
            time.setFrameIcon(null);
            try {
                time.name_cinima.setText(movies.getBookById(2).getName());
            } catch (SQLException ex) {
                Logger.getLogger(MoviesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            BasicInternalFrameUI ui = (BasicInternalFrameUI) time.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(time);
            time.setLocation(this.getWidth()/2 - time.getWidth()/2, this.getHeight()/2 - time.getHeight()/2);
            
            time.setVisible(true);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jLabel_Image_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Image_4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Image_4MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if (time == null || time.isClosed()) {

            time.setTitle("Majar Cineplex");
            time.setFrameIcon(null);
            try {
                time.name_cinima.setText(movies.getBookById(3).getName());
            } catch (SQLException ex) {
                Logger.getLogger(MoviesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            BasicInternalFrameUI ui = (BasicInternalFrameUI) time.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(time);

            time.setVisible(true);
        } else {
           time.setTitle("Majar Cineplex");
            time.setFrameIcon(null);
            try {
                time.name_cinima.setText(movies.getBookById(3).getName());
            } catch (SQLException ex) {
                Logger.getLogger(MoviesForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            BasicInternalFrameUI ui = (BasicInternalFrameUI) time.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(time);
            time.setLocation(this.getWidth()/2 - time.getWidth()/2, this.getHeight()/2 - time.getHeight()/2);
            
            time.setVisible(true);
        }
        //time.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jLabel_Image_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Image_8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Image_8MouseClicked

    private void ReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewActionPerformed
        // TODO add your handling code here:
         if (review == null || review.isClosed()) {

            review.setTitle("Majar Cineplex");
            review.setFrameIcon(null);
            BasicInternalFrameUI ui = (BasicInternalFrameUI) review.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(review);

            review.setVisible(true);
        } else {
            review.setTitle("Majar Cineplex");
            review.setFrameIcon(null);
            BasicInternalFrameUI ui = (BasicInternalFrameUI) review.getUI();
            Container north = (Container) ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            desktopPane.add(review);
            review.setLocation(this.getWidth()/2 - review.getWidth()/2, this.getHeight()/2 - review.getHeight()/2);
            
            review.setVisible(true);
        }
    }//GEN-LAST:event_ReviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoviesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoviesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoviesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoviesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MoviesForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MoviesForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Review;
    private javax.swing.JDesktopPane desktopPane;
    private rojerusan.RSMaterialButtonRectangle genre1;
    private rojerusan.RSMaterialButtonRectangle genre2;
    private rojerusan.RSMaterialButtonRectangle genre3;
    private rojerusan.RSMaterialButtonRectangle genre4;
    private rojerusan.RSMaterialButtonRectangle genre5;
    private rojerusan.RSMaterialButtonRectangle genre6;
    private rojerusan.RSMaterialButtonRectangle jButton10;
    private rojerusan.RSMaterialButtonRectangle jButton11;
    private rojerusan.RSMaterialButtonRectangle jButton12;
    private rojerusan.RSMaterialButtonRectangle jButton7;
    private rojerusan.RSMaterialButtonRectangle jButton8;
    private rojerusan.RSMaterialButtonRectangle jButton9;
    private javax.swing.JButton jButton_Books_List_;
    private javax.swing.JButton jButton_Books_List_1;
    private javax.swing.JButton jButton_Books_List_4;
    private javax.swing.JButton jButton_Books_List_5;
    private javax.swing.JButton jButton_Members_List_;
    private javax.swing.JButton jLabel1;
    private javax.swing.JButton jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JButton jLabel5;
    private javax.swing.JButton jLabel6;
    private javax.swing.JButton jLabel7;
    private javax.swing.JButton jLabel8;
    private javax.swing.JLabel jLabel_Dashboard_user;
    private javax.swing.JLabel jLabel_Image_1;
    private javax.swing.JLabel jLabel_Image_3;
    private javax.swing.JLabel jLabel_Image_4;
    private javax.swing.JLabel jLabel_Image_5;
    private javax.swing.JLabel jLabel_Image_6;
    private javax.swing.JLabel jLabel_Image_7;
    private javax.swing.JLabel jLabel_Image_8;
    public javax.swing.JTextField jLabel_WelcomeUsername;
    public javax.swing.JTextField jLabel_WelcomeUsername1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JMenuBar menuBar;
    private rojerusan.RSMaterialButtonRectangle time1;
    private rojerusan.RSMaterialButtonRectangle time2;
    private rojerusan.RSMaterialButtonRectangle time3;
    private rojerusan.RSMaterialButtonRectangle time4;
    private rojerusan.RSMaterialButtonRectangle time5;
    private rojerusan.RSMaterialButtonRectangle time6;
    // End of variables declaration//GEN-END:variables

}
