package My_Forms;

import My_Classes.Func_Class;
import My_Classes.ticket;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author ACER N026
 */
public class MyTicketForm extends javax.swing.JInternalFrame {

    My_Classes.Func_Class func = new Func_Class();

    My_Classes.Member member = new My_Classes.Member();

    My_Classes.ticket mov = new My_Classes.ticket();

    /**
     * Creates new form MyTicket
     */
    public MyTicketForm() {
        initComponents();
       

        func.displayImage(74, 47, null, "/My_Images/Rectangle 233.png", jLabel2);
        populateJtableWithMembers("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evaluatorRectangle2D1 = new org.jdesktop.swing.animation.timing.evaluators.EvaluatorRectangle2D();
        evaluatorRectangle2D2 = new org.jdesktop.swing.animation.timing.evaluators.EvaluatorRectangle2D();
        evaluatorRectangle2D3 = new org.jdesktop.swing.animation.timing.evaluators.EvaluatorRectangle2D();
        rSButtonPaneBeanInfo1 = new rojerusan.RSButtonPaneBeanInfo();
        rSPanelImageBeanInfo1 = new rojerusan.RSPanelImageBeanInfo();
        rSEstiloTablaHeader1 = new rojeru_san.complementos.RSEstiloTablaHeader();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_CloseForm_ = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Members_ = new javax.swing.JTable();
        jLabel_CloseForm_1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(176, 175, 187));
        setIconifiable(true);

        jPanel2.setBackground(new java.awt.Color(31, 29, 54));

        jLabel1.setFont(new java.awt.Font("Prompt", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My ticket");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_Images/Rectangle 233.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel_CloseForm_.setBackground(new java.awt.Color(153, 204, 255));
        jLabel_CloseForm_.setFont(new java.awt.Font("Pridi SemiBold", 1, 16)); // NOI18N
        jLabel_CloseForm_.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CloseForm_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseForm_.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 389, Short.MAX_VALUE)
                    .addComponent(jLabel_CloseForm_)
                    .addGap(0, 389, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 39, Short.MAX_VALUE)
                    .addComponent(jLabel_CloseForm_)
                    .addGap(0, 39, Short.MAX_VALUE)))
        );

        jTable_Members_.setBackground(new java.awt.Color(0, 255, 255));
        jTable_Members_.setFont(new java.awt.Font("Prompt", 1, 14)); // NOI18N
        jTable_Members_.setForeground(new java.awt.Color(255, 255, 255));
        jTable_Members_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Members_.setToolTipText("");
        jTable_Members_.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_Members_.setRowHeight(30);
        jTable_Members_.setRowMargin(2);
        jTable_Members_.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable_Members_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Members_MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Members_);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        jLabel_CloseForm_1.setBackground(new java.awt.Color(31, 29, 54));
        jLabel_CloseForm_1.setFont(new java.awt.Font("Pridi SemiBold", 1, 16)); // NOI18N
        jLabel_CloseForm_1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CloseForm_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm_1.setText("X");
        jLabel_CloseForm_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseForm_1.setOpaque(true);
        jLabel_CloseForm_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseForm_1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_CloseForm_1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_CloseForm_1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseForm_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseForm_1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseForm_1MouseClicked

    private void jTable_Members_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Members_MouseClicked
        My_Forms.Ticketcard mtic = new My_Forms.Ticketcard();
        My_Classes.ticket tic = new My_Classes.ticket();
        My_Classes.ticket SelectedMember;

        try {

            jTable_Members_.setSelectionBackground(new Color(31, 29, 54));
            jTable_Members_.setGridColor(Color.GRAY);
            Integer rowIndex = jTable_Members_.getSelectedRow();
            Integer id = Integer.parseInt(jTable_Members_.getModel().getValueAt(rowIndex, 0).toString());
            SelectedMember = tic.getticById(id);
            System.out.println(SelectedMember);
            if (SelectedMember != null) {
                //System.out.println(ticket.SelectedMember.getMovie_name());
                mtic.jTextField1.setText(SelectedMember.getMovie_name());
                mtic.jTextField1.setEditable(false);
                mtic.jTextField3.setText(SelectedMember.getCinema_name());
                mtic.jTextField3.setEditable(false);
                mtic.jTextField2.setText(SelectedMember.getSeat());
                mtic.jTextField2.setEditable(false);
                mtic.jTextField4.setText(SelectedMember.getDate());
                mtic.jTextField4.setEditable(false);
                mtic.jTextField5.setText(SelectedMember.getTime());
                mtic.jTextField5.setEditable(false);
                mtic.setVisible(true);
               
            }else {
                JOptionPane.showMessageDialog(null, "Not Found", "Invalid ticket", 3);
            }

        } catch (SQLException | NumberFormatException ex) {
            //Logger.getLogger(EditMemberForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Enter a Valid Member Id", "Invalid Id", 3);
        }
    }//GEN-LAST:event_jTable_Members_MouseClicked
    public static void main(String[] args) {
        new MyTicketForm().setVisible(true);
    }

    public void populateJtableWithMembers(String query) {

        ArrayList<My_Classes.ticket> ticketsList = mov.ticketsList(query);
//        ArrayList<My_Classes.Member> membersList = member.membersList(query);
        String[] colNames = {"ID", "Movie-name", "Cinema", "Seat no.", "Showtime", "Date"};
        Object[][] rows = new Object[ticketsList.size()][colNames.length];
        jTable_Members_.setGridColor(Color.GRAY);

        for (int i = 0; i < ticketsList.size(); i++) {
            rows[i][0] = ticketsList.get(i).getId();

            rows[i][1] = ticketsList.get(i).getMovie_name();

            rows[i][2] = ticketsList.get(i).getCinema_name();

            rows[i][3] = ticketsList.get(i).getSeat();

            rows[i][4] = ticketsList.get(i).getTime();

            rows[i][5] = ticketsList.get(i).getDate();

        }

        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_Members_.setBackground(new Color(80, 100, 122));
        jTable_Members_.setSelectionBackground(new Color(31, 29, 54));
        jTable_Members_.getTableHeader().setOpaque(false);
        jTable_Members_.getTableHeader().setBackground(new Color(246, 246, 246));
        jTable_Members_.setModel(model);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swing.animation.timing.evaluators.EvaluatorRectangle2D evaluatorRectangle2D1;
    private org.jdesktop.swing.animation.timing.evaluators.EvaluatorRectangle2D evaluatorRectangle2D2;
    private org.jdesktop.swing.animation.timing.evaluators.EvaluatorRectangle2D evaluatorRectangle2D3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_CloseForm_;
    private javax.swing.JLabel jLabel_CloseForm_1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable_Members_;
    private rojerusan.RSButtonPaneBeanInfo rSButtonPaneBeanInfo1;
    private rojeru_san.complementos.RSEstiloTablaHeader rSEstiloTablaHeader1;
    private rojerusan.RSPanelImageBeanInfo rSPanelImageBeanInfo1;
    // End of variables declaration//GEN-END:variables

    
}
